/**
 * Mirrors the Odometer privacy policy and terms of use from legal.neuera.app
 * into src/pages/privacy.html and src/pages/terms.html, so build-pages.mjs
 * wraps them in the site template like any other page.
 *
 * Same mechanism as the Kalum and Play Lounge sites:
 *   - fetch the source page, pull out <article class="legal-document
 *     current-document">, drop anything executable, rewrite cross-references
 *     onto this site's /privacy/ and /terms/ paths;
 *   - the rendered page canonicalizes back to legal.neuera.app, which stays
 *     the source of truth (and keeps every version archived);
 *   - on fetch failure, the existing fragment is kept as the last-known-good
 *     copy. A fresh clone with no fragment and no network fails loudly.
 *
 * Runs as the first step of `npm run build`; also `npm run sync:legal`.
 * The document text is copied verbatim — nothing here edits legal wording.
 */

import { readFile, writeFile, access } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const LEGAL = 'https://legal.neuera.app'

const SOURCES = [
  {
    slug: 'privacy',
    url: `${LEGAL}/odometer/privacy/`,
    title: 'Privacy Policy — Odometer',
    breadcrumb: 'Privacy Policy',
    description:
      'How Odometer handles your data: local-only storage, no account, no cloud sync, and optional single location snapshots.',
  },
  {
    slug: 'terms',
    url: `${LEGAL}/odometer/terms/`,
    title: 'Terms of Use — Odometer',
    breadcrumb: 'Terms of Use',
    description: 'The terms governing your use of the Odometer mileage tracking app.',
  },
]

const ARTICLE_RE = /<article\s+class="legal-document current-document"[\s\S]*?<\/article>/i

/** Extract, sanitize and re-point the article. Throws if it is not found. */
function prepare(html, { url }) {
  const match = html.match(ARTICLE_RE)
  if (!match) throw new Error('no <article class="legal-document current-document"> in source')
  let body = match[0]

  // Defense in depth: nothing executable rides along.
  body = body.replace(/<script[\s\S]*?<\/script>/gi, '').replace(/\son\w+="[^"]*"/gi, '')

  // Cross-references between the two documents point at this site's copies.
  body = body
    .replace(/https:\/\/legal\.neuera\.app\/odometer\/privacy\/?(?=["#])/gi, '/privacy/')
    .replace(/https:\/\/legal\.neuera\.app\/odometer\/terms\/?(?=["#])/gi, '/terms/')
    .replace(/href="\/odometer\/privacy\/?"/gi, 'href="/privacy/"')
    .replace(/href="\/odometer\/terms\/?"/gi, 'href="/terms/"')

  // Version-history links go back to the archive on the source site, where the
  // relative href actually resolves.
  const archive = url.replace(/\/$/, '') + '/archive.html'
  body = body.replace(/href="\.?\/?archive\.html"/gi, `href="${archive}"`)

  // The source outline starts at <h2> (its <h1> is the host site's). Promote
  // one level so the page has exactly one h1 and no skipped levels.
  body = body
    .replace(/<(\/?)h2(\s|>)/gi, '<$1h1$2')
    .replace(/<(\/?)h3(\s|>)/gi, '<$1h2$2')
    .replace(/<(\/?)h4(\s|>)/gi, '<$1h3$2')

  const version = body.match(/data-version="([^"]+)"/)?.[1] ?? null
  return { body, version }
}

function fragment(src, { body, version }, syncedAt) {
  const meta = {
    slug: src.slug,
    breadcrumb: src.breadcrumb,
    title: src.title,
    description: src.description,
    // legal.neuera.app is the source of truth — consolidate signals there.
    canonical: src.url,
    ogType: 'website',
    jsonld: 'minimal',
    source: src.url,
    version,
    synced: syncedAt,
  }
  const syncedHuman = new Date(syncedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC',
  })
  return `<!--meta
${JSON.stringify(meta, null, 2)}
-->
        <!-- GENERATED by scripts/fetch-legal.mjs from ${src.url} — do not edit by hand. -->
        <nav aria-label="Breadcrumb" class="max-w-3xl mx-auto px-6 pt-10">
            <ol class="flex items-center gap-2 text-sm text-gray-500">
                <li><a href="{{BASE}}" class="hover:text-gray-300 transition-colors">Odometer</a></li>
                <li aria-hidden="true" class="text-gray-700">/</li>
                <li class="text-gray-400" aria-current="page">${src.breadcrumb}</li>
            </ol>
        </nav>

        <section class="pt-8 pb-24 px-6">
            <div class="max-w-3xl mx-auto">
                <div class="glass-card rounded-[2rem] p-6 md:p-12 legal-wrap">
${body}
                </div>
                <p class="text-gray-500 text-sm mt-8 leading-relaxed">
                    Source of truth:
                    <a href="${src.url}" class="text-primary-400 hover:text-primary-300 underline underline-offset-2">${src.url.replace('https://', '')}</a>
                    &mdash; every version is archived there. This copy was last synced ${syncedHuman}.
                </p>
            </div>
        </section>
`
}

async function exists(p) {
  try { await access(p); return true } catch { return false }
}

async function syncOne(src) {
  const out = join(ROOT, 'src/pages', `${src.slug}.html`)
  const label = src.slug.padEnd(8)
  try {
    const res = await fetch(src.url, { headers: { 'User-Agent': 'odo-landing build' } })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const prepared = prepare(await res.text(), src)
    const syncedAt = new Date().toISOString().slice(0, 10)
    const next = fragment(src, prepared, syncedAt)

    // Don't churn the synced date when the document itself is unchanged —
    // that would restamp the file (and the page) on every build.
    if (await exists(out)) {
      const prev = await readFile(out, 'utf8')
      const strip = (s) => s.replace(/"synced": "[^"]+"/, '').replace(/last synced [^.]+\./, '')
      if (strip(prev) === strip(next)) {
        console.log(`  ${label} unchanged (version ${prepared.version})`)
        return true
      }
    }
    await writeFile(out, next)
    console.log(`  ${label} synced   (version ${prepared.version}, ${(prepared.body.length / 1024).toFixed(1)} kB)`)
    return true
  } catch (err) {
    if (await exists(out)) {
      console.log(`  ${label} FETCH FAILED (${err.message}) — keeping the existing copy`)
      return true
    }
    console.error(`  ${label} FETCH FAILED (${err.message}) and no cached copy exists`)
    return false
  }
}

console.log('Syncing legal pages from legal.neuera.app:')
const ok = await Promise.all(SOURCES.map(syncOne))
if (ok.includes(false)) {
  console.error('Aborting: a legal page could not be synced and nothing is cached.')
  process.exit(1)
}
